Add rebalance metrics for Kafka consumers
RedHatInsights/insights-core-messaging pull request #48
Opened 2023-12-20 16:43 UTC by wcmitchell

As rebalancing is a disruptive but necessary part of Kafka's ConsumerGroup functionality, keeping tabs on their frequency and effect on a Kafka consumer's operation queue size can offer extra insight into the health of the ecosystem. This attempts to configure and enable pertinent Prometheus metrics, though individual applications will need to expose those metrics to be scraped.

2023-12-20 16:45 UTC, wcmitchell commented
This is a first swing after a lot of trial and error with testing confluent_kafka, librdkafka, and the stats_cb functionality. See the following documentation for more information:

https://github.com/confluentinc/librdkafka/blob/master/STATISTICS.md
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#kafka-client-configuration

2024-01-26 02:20 UTC, csams commented
Hey @wcmitchell have you had a look at the engine library that uses this one? It might make more sense to put this functionality there.

2024-01-30 16:09 UTC, csams requested changes
I have a question about the `stats_to_metrics` function. Also, do you mind making the collection interval configurable?

2024-01-30 20:32 UTC, wcmitchell commented on insights_messaging/consumers/kafka.py
> +        config["statistics.interval.ms"] = 10000 # Gather metrics every 10 secs
Yep, can do!

2024-01-31 01:09 UTC, wcmitchell commented on insights_messaging/consumers/kafka.py
> +        stat_type = self.stats.get('type')
Good catch! We don't want to keep the stats object around, just get it loaded into the metrics. Updated!

2024-02-28 22:15 UTC, csams approved these changes

2024-02-28 22:16 UTC, merged